black_cat:
  github:
    org_names:
      - 'octocat'
    access_token: ''
  logging:
    splunk:
      domain: ''
      port: 8888
      proto: 'https'
      index: 'blackcat'
      source_type: 'blackcat'
      hec_token: ''
      enabled: true
