apiVersion: v1
kind: Secret
metadata:
  name: blackcat-secret
type: Opaque
data:
  splunk_domain: ''
  splunk_port: 8888
  splunk_hec: 'ZXhhbXBsZSAtbgo='
  git_token: 'ZXhhbXBsZS1naXQtYWNjZXNzLXRva2VuCg=='
  org_names: 'octocat,github'